version: '3.8'

services:
  myapp:
    depends_on: 
      - mysql
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: myapp
    hostname: myapp
    networks:
      - mynet
    volumes:
      - ./config/config.yaml:/config/config.yaml
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    networks:
      - mynet
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ahmet
    volumes:
      - ./data/my.cnf:/etc/my.cnf
      - ./data/mysql:/var/lib/mysql
    restart: unless-stopped

networks:
  mynet:
    driver: bridge