replicaCount: 1

image:
  repository: nginx
  tag: "1.16.0"
  pullPolicy: IfNotPresent

service:
  name: nginx-service
  type: ClusterIP
  port: 80
  targetPort: 9000

ports:
  http:
    name: http
    port: 80
    protocol: TCP

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

probe:
  livenessProbe:
    httpGet:
      path: /
      port: 80
      httpHeaders:
        name: Accept
        value: ""
    failureThreshold: 1
    periodSeconds: 10
  startupProbe:
    httpGet:
      path: /
      port: 80
      httpHeaders:
        name: User-Agent
        value: ""
    failureThreshold: 30
    periodSeconds: 10

env:
  name: dev
