app:
  name: myapp

server:
  server_username: root
  server_password: ahmet
  server_host: 192.168.122.10
  server_port: 22
  server_file_path: /home/kubernetmachinetwo/asd.txt

website:
  url: https://ahmetozyoruk.me

database:
  db_host: mysql
  db_port: 3306
  db_name: myapp
  db_username: root
  db_password: ahmet