apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-index-html-configmap
  namespace: default
data:
  index.html: |
    <html>
    <h1>Second Attempt</h1>
    </br>
    <h1>Hi! I got deployed Second Attempt in {{ .Values.env.name }} Environment using Helm Chart </h1>
    </html>
