all:
  hosts:
    node1:
      ansible_host: 192.168.122.241
      ip: 192.168.122.241
      access_ip: 192.168.122.241
    node2:
      ansible_host: 192.168.122.242
      ip: 192.168.122.242
      access_ip: 192.168.122.242
    node3:
      ansible_host: 192.168.122.243
      ip: 192.168.122.243
      access_ip: 192.168.122.243
    node4:
      ansible_host: 192.168.122.244
      ip: 192.168.122.244
      access_ip: 192.168.122.244
    node5:
      ansible_host: 192.168.122.245
      ip: 192.168.122.245
      access_ip: 192.168.122.245
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
