apiVersion: v1
kind: PersistentVolume
metadata:
  name: falco-falcosidekick-ui-redis-data-falco-falcosidekick-ui-redis-0
  namespace: falco
spec:
  accessModes:
   - ReadWriteOnce
  capacity:
   storage: 1Gi
  volumeMode: Filesystem
  hostPath:
    path: /data
