apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-deployment-configmap-rw-role
  namespace: usy-namespace
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "create", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-deployment-configmap-rw-binding
  namespace: usy-namespace
subjects:
- kind: User
  name: ahmetozyoruk3@gmail.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-deployment-configmap-rw-role
  apiGroup: rbac.authorization.k8s.io
