apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-deployment-read-role
  namespace: usy-tmp-namespace
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-deployment-read-binding
  namespace: usy-tmp-namespace
subjects:
- kind: User
  name: ahmetozyoruk61@gmail.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-deployment-read-role
  apiGroup: rbac.authorization.k8s.io
