apiVersion: v1
kind: Service
metadata:
  name: magento
  namespace: {{ .Release.Namespace }}-magento-app
spec:
  selector:
    app: magento
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
