apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ .Release.Namespace }}-magento-app
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      name: db
      port: 9200
      targetPort: 9200
    - protocol: TCP
      name: monitoring
      port: 9300
      targetPort: 9300
